### ISSUE TITLE
Cosult

### ISSUE THREAD

**Issue by joseliko7** [appticles/wordpress-mobile-pack-backend#1]
I want to help improve the plugin.
But I can not do it without the Pro version.

As I need to test and try...
What do I do to get Pro version?

**Comment by anghelalexandra** [comment]
Hi there,

The Pro plugin sources are not publicly available. The functionality of the Pro plugin is similar to the free version, so you can get a good idea of how it works by testing the free plugin and watching the presentation videos. 

We also have a [15% discount offer on the Pro plugin](https://www.appticles.com/wordpress-mobile-pack-pro.html?code=5f5ac723adb7b52166d34167ca22cbc7), available until the end of October.
