### ISSUE TITLE
Some export categories tests fail on older WordPress version

### ISSUE THREAD

**Issue by anghelalexandra** [appticles/wordpress-mobile-pack-backend#14]
The following tests are failing on WP 3.6 and 3.8, even though the export categories endpoint seems to be working correctly:

- ExportCategoriesTest::test_export_categories_returns_correct_if_page_and_rows_are_given
- ExportCategoriesTest::test_export_categories_returns_empty_and_page_and_rows_as_parameters_in_json_if_page_too_high

The error message is "Object of class stdClass could not be converted to int" from wp-includes/taxonomy.php.

**Comment by EkoAlex** [comment]
Solved by 62a74622ba9f6e8e9e344c5ab42fbe52cf817dc7
