### ISSUE TITLE
Update purifier to the latest version to include support for PHP7

### ISSUE THREAD

**Issue by anghelalexandra** [appticles/wordpress-mobile-pack-backend#22]
Also, use purifier only where it is needed, not for saniziting callback names.

Ex. in export/content.php, replace

$callback = $export->purifier->purify($_GET['callback']);

with
$callback = filter_var($_GET['callback'], FILTER_SANITIZE_STRING);

See also class-export.php.

**Comment by EkoAlex** [comment]
Closed in ea6db311340f8e498bc14083c82f8125b2e8ccb7
